web:
  extends:
    file: docker-compose.common.yml
    service: web
  volumes:
    - ./src:/app/user/src
  environment:
    NODE_ENV: 'development'
    PROXY_PORT: 3001
    HOST: http://localhost:3000
  ports:
    - '3000:3001'
    - '5000:3000' #Direct access to node server for debugging
    - '8080:8080'
  tty: true
  stdin_open: true
  read_only: false
#   links:
#     - herokuPostgresql
#     - herokuRedis
# herokuPostgresql:
#   ports:
#     - '5432:5432'
#   extends:
#     file: docker-compose.common.yml
#     service: herokuPostgresql
# herokuRedis:
#   image: redis
#   extends:
#     file: docker-compose.common.yml
#     service: herokuRedis
